### ISSUE TITLE
Method isoFormat not exists on fresh installation laravel 5.8.3 and boilerplate

### ISSUE THREAD

**Issue by sonicalabs** [sebastienheyd/boilerplate#13]
Hi again Sebastien !!

Only for your information:
Trying to understand what's happening with my routes under Laravel I run a fresh installation of laravel 5.8.3 and boilerplate package as local project under Vagrant, published assets and run migration. Not installed anything else.
After register a new user, and logged in I go to user section and laravel throw this exception message. Only for your information.

![imagen](https://user-images.githubusercontent.com/24943372/55418161-5e67bb80-5572-11e9-8bc9-8d48518faa25.png)

Entering on userprofile get this exception error
![imagen](https://user-images.githubusercontent.com/24943372/55419859-f74c0600-5575-11e9-9eac-15249b20024d.png)

As a read, isoFormat method is only available on Carbon 2, and is supposed to be installed as default carbon versión with Laravel 5.8.

This is my composer.json

![imagen](https://user-images.githubusercontent.com/24943372/55419617-6d03a200-5575-11e9-804f-8714698650ab.png)

I'm sure this is not related to boilerplate, seems more a laravel/carbon integration error, but affects to boilerplate after you switch on use isoFormat method to format dates as you explain in readme.

If I get some light about this.. drop u a note here.

**Comment by sebastienheyd** [comment]
Can you check the version of nesbot/carbon ?

```
composer show nesbot/*
```

And your version of PHP ? Carbon2 require php >= 7.1.8

**Comment by sebastienheyd** [comment]
https://github.com/sebastienheyd/boilerplate/releases/tag/5.8.3

Carbon 2 is now a requirement
