### ISSUE TITLE
 php artisan migrate

### ISSUE THREAD

**Issue by khowal** [sebastienheyd/boilerplate#2]
When I ran php artisan migrate, it resulted in the following error

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by sebastienheyd** [comment]
The answer is here : https://github.com/sebastienheyd/boilerplate/blob/5.4/README.md#troubleshooting
