### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by agungsugiarto** [sebastienheyd/boilerplate#20]
Please add permission management like create, update, delete. Thanks!

**Comment by sebastienheyd** [comment]
Can you explain to me why you need this feature?

In my opinion, permissions are intimately tied to the code. For example, you will write: 

```php
if($user->can('edit-user')) {
   // ...
}
```

In this example, imagine you can delete or update the "edit-user" permission in a control panel, the condition will never return true anymore and the code inside never executed anymore. This is why, in my opinion, users must not be able to manage permission in the back office.

I use migration like [this one](https://github.com/sebastienheyd/boilerplate/blob/master/src/migrations/2017_04_18_171649_log_viewer_permission.php) or [this one](https://github.com/sebastienheyd/boilerplate-email-editor/blob/master/src/migrations/2019_02_05_130934_emails_permissions.php) (from another package) to add permissions to my projects. This is a good solution to deliver permissions with your code.
