### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by agungsugiarto** [sebastienheyd/boilerplate#22]
How to best way, for add some new plugin assets?

**Comment by sebastienheyd** [comment]
In your application the easiest way is to push to the js or css stack. In your views where you need the assets add :

```blade
@push('js')
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'editor1' );
    </script>
@endpush
```

Or for css (with a local file) :

```blade
@push('css')
    <link rel="stylesheet" href="styles.css" type="text/css">
    <style>
        body { background: red }
    </style>
@endpush
```
You can call local assets by putting them in the public directory.

Is that the answer you've been waiting for?

**Comment by agungsugiarto** [comment]
Thanks, its help me. Closed.
