### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by neapolis79** [sebastienheyd/boilerplate#23]
Hi,
i would know if the package will be updated to include support to the new version of laravel, 7.x.

Thanks in advance

**Comment by sebastienheyd** [comment]
Yes, this will come soon. I waited for the dependencies to be upgraded to version 7 as well.

The main difference will be the use of the new Blade component tag.

**Comment by sebastienheyd** [comment]
Laravel 7 is now supported.

https://github.com/sebastienheyd/boilerplate/releases/tag/7.1.0
