### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by kinzinho666** [sebastienheyd/boilerplate#24]
Nice job, exactly i neeed, but i dont understand how to create new module out of vendor/sebastian....

Module "Product"  with CRUD (in app/controllers/products, app/productModel and resource/views/productsViews) and create permission for this module in roles:

mysite.com/roles/create:

```
PRODUCT
|___| Create
|___| Read
|___| Update
|___| Delete
|___| Browser (if not checked, hide menu product and block access page)
```

**Comment by sebastienheyd** [comment]
Hi, thanks ! hope this package will meet your needs.

What you want is certainly create a package to use it like a module? At the moment, I'm writing the new documentation, I'll add a tutorial for the package creation: https://sebastienheyd.github.io/boilerplate/

Here's how I would do it:

- create the new package "Product" in a packages folder (why don't use an another package to do that: https://github.com/Jeroen-G/laravel-packager - I just found it now, maybe it will be interesting to add a CLI command with my package directly). 

- create the migrations to create the permissions in the database in your freshly created package. You have an example in one of my other packages: https://github.com/sebastienheyd/boilerplate-email-editor/blob/master/src/migrations/2019_02_05_130934_emails_permissions.php 

- declare migrations in your package service provider : https://github.com/sebastienheyd/boilerplate-email-editor/blob/66c4f09eaf352f9bfe6d2df210c9e675a69176c5/src/ServiceProvider.php#L21

- create the controllers and associated routes in your package, ex: https://github.com/sebastienheyd/boilerplate-email-editor/blob/master/src/routes/boilerplate-email-editor.php

- declare routes in your in your package service provider : https://github.com/sebastienheyd/boilerplate-email-editor/blob/66c4f09eaf352f9bfe6d2df210c9e675a69176c5/src/ServiceProvider.php#L18

- create the menu item by using the CLI command : https://sebastienheyd.github.io/boilerplate/howto/add-menu-items (don't forget to move generated class in your package)

- check permissions on menu item : https://github.com/sebastienheyd/boilerplate-email-editor/blob/66c4f09eaf352f9bfe6d2df210c9e675a69176c5/src/Menu/BoilerplateEmailEditor.php#L12

- check permissions on controllers : https://github.com/sebastienheyd/boilerplate-email-editor/blob/66c4f09eaf352f9bfe6d2df210c9e675a69176c5/src/Controllers/EmailController.php#L21

Permissions and roles are provided by Laratrust : https://laratrust.santigarcor.me/docs/6.x/

Hope this will help you...

**Comment by sebastienheyd** [comment]
To make it easier I just release a new package that will allows you to build packages (aka modules) for boilerplate with one artisan command.

https://github.com/sebastienheyd/boilerplate-packager

This will build a package where you can code directly you features. Don't hesitate to send me feedback.
