### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by Plasto13** [sebastienheyd/boilerplate#26]
it is possible to add support for [laravel Datatables](https://github.com/yajra/laravel-datatables) and[ Laravel package for translatable models](https://github.com/Astrotomic/laravel-translatable) ???

**Comment by sebastienheyd** [comment]
Laravel Datatables is already supported. Have a look to my other package [boilerplate-packager)](https://github.com/sebastienheyd/boilerplate-packager) that will help you to create package for boilerplate, if you generate one package you will see that datatables is used.

I'll take a look at the other package, it can be interesting in a project. However we don't have the use of it here because we don't have a model to translate in this package, or at least I don't see the use of it here.

The translation is more interesting if we create, for example, a package to manage multilingual articles, that's where we'll call it.

**Comment by Plasto13** [comment]
I almost meant implementation as a [service](https://datatables.yajrabox.com/service). 
For better implementation of filtering, buttons, colReorder and much more in one class. I can imagine translatable models in a multilingual website with articles and can also be added to a datatable search.

```
public function applyScopes($query)
    {
        $request = request();

        $requestFilters = [];

        if ($request->has('filter_columns') && ($request->input('filter_table_id'))) {
            $requestFilters = [];
            foreach ($request->input('filter_columns') as $key => $column) {
                $requestFilters[] = [
                    'column'   => $column,
                    'operator' => $request->input('filter_operators.' . $key),
                    'value'    => $request->input('filter_values.' . $key),
                ];
            }
        }

        foreach ($requestFilters as $requestFilter) {
            if (isset($requestFilter['column']) && !empty($requestFilter['column'])) {
                $query = $this->applyFilterCondition($query, $requestFilter['column'], $requestFilter['operator'],
                    $requestFilter['value']);
            }
        }

        return parent::applyScopes($query);
    }
```

**Comment by sebastienheyd** [comment]
Maybe I don't understand the problem, for me datatables is already accessible as you can see here:

https://github.com/sebastienheyd/boilerplate/blob/f1f9094e7be0e19a98320e50768842bcbc61b949/composer.json#L13-L14

**Comment by Plasto13** [comment]
Yes, I know. I almost thought to generate for each model to create a datatables class. To the Datatables directory. I have developed one class with additional javascript for working filters and bulk changes.
He is still in the proposal.
[https://github.com/Plasto13/datatables/blob/master/TestDatatables](https://github.com/Plasto13/datatables/blob/master/TestDatatables)
I do this in asgardCSM. But he no longer goes to the higher version of Laravel

**Comment by sebastienheyd** [comment]
The version [7.10.0](https://github.com/sebastienheyd/boilerplate/releases/tag/7.10.0) comes with a new [datatable component](https://sebastienheyd.github.io/boilerplate/components/datatable) to generate a datatable with a class.

You can now generate your own datatable class with the artisan command [boilerplate:datatable](https://sebastienheyd.github.io/boilerplate/datatables/create) and easily build a datatable.

As you can see filters are automatically added. I will probably add more filter types in the future.

You can have a look to the [UsersDatatable class](https://github.com/sebastienheyd/boilerplate/blob/master/src/Datatables/UsersDatatable.php) as an example.
