### ISSUE TITLE
Getting below error when submits registration form

### ISSUE THREAD

**Issue by khowal** [sebastienheyd/boilerplate#3]
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at` ▶"

**Comment by sebastienheyd** [comment]
I need more details, which version of Laravel and Boilerplate, stacktrace, list of routes, ...

Normally, there is no field `name` but two fields, a field `last_name` and a field `first_name`. Look in the tables generated by `migrate`. Do you see these two fields in the register form ?

In addition, it seems that the executed action is not the right one, it looks like the original register action of Laravel. In your routes you must have a route called `register.post` pointing to  `Sebastienheyd\Boilerplate\Controllers\Auth\RegisterController@register` , do you have cache ?

**Comment by khowal** [comment]
I am using Laravel Framework 5.5.25 . Please accept my apologies for the trouble.  I have an idea on which I am working. After researching I found laravel should be perfect for the project because of its packages. To get the basic skeleton of the application. I needed this module. I know basic php and generic programming. I learnt to implement modules available on github. Your's is first.  Let me try drop what make:auth has generated.

**Comment by khowal** [comment]
Thanks ! Removal of make:auth resolved the issue.
