### ISSUE TITLE
User new field

### ISSUE THREAD

**Issue by ruospo** [sebastienheyd/boilerplate#31]
how i can add new fillable column to users model with boilerplate?
i have create migrate, after i have override view but i need to seet fillable.

**Comment by sebastienheyd** [comment]
You have to override the login / register routes, then you can use your own controller with your own validation rules, views and models.

If you do so, you have to declare your models to Laratrust, check the laratrust.php config file.

The routes must be instantiated before boilerplate's routes, to do that you can add your call in app/Providers/RouteServiceProvider.php

I will think about this issue, probably I will add a config option to use your own models and controller for login

**Comment by sebastienheyd** [comment]
It will be something like that :

```php
$default = [
    'prefix'    => config('boilerplate.app.prefix', ''),
    'domain'    => config('boilerplate.app.domain', ''),
    'namespace' => 'Namespace\To\Your\Controllers',
    'as'        => 'boilerplate.'
];

Route::group(array_merge($default, ['middleware' => ['web', 'boilerplatelocale']]), function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
});
```
