### ISSUE TITLE
Error when add lang

### ISSUE THREAD

**Issue by bonaxcrimo** [sebastienheyd/boilerplate#34]
I have error like this when add lang

https://flareapp.io/share/17WgKG87#F79

When i check because this line

 $title = sprintf('<p>%s</p>', /** @scrutinizer ignore-type */ __($title));

**Comment by sebastienheyd** [comment]
Do you have a file named Category.php in your lang folder ?

The error comes from the function __() that is a function from Laravel. If you have a file Category.php with an array of translations into it, Laravel will think that you call the array in Category.php instead of a simple string.

**Comment by bonaxcrimo** [comment]
yes sir,error because i don't use lang in menu just simple string
