### ISSUE TITLE
Way to disable log

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#38]
Is there a way to disable logs?

**Comment by sebastienheyd** [comment]
For the moment no, but it's a good point, we don't necessarily need to use a default log system

It's not too hard to implement, I'll see about adding a configuration option to disable the logs.

**Comment by thracefields** [comment]
Could you suggest me a solution for the moment? I tried deleting the log routes, controllers and views, but that's not working.

**Comment by sebastienheyd** [comment]
Job done !

https://github.com/sebastienheyd/boilerplate/releases/tag/7.5.4

All you have to do now is to update the package to v7.5.4, add a `logs` parameter in `config/boilerplate/app.php` and set it to `false`
