### ISSUE TITLE
Way to change languages

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#39]
Could you suggest me a way to change languages? I'm following this tutorial: [https://5balloons.info/localization-laravel-multi-language-language-switcher/](https://5balloons.info/localization-laravel-multi-language-language-switcher/), but the effect is that it keeps the default locale. If I change the locale in the config file, everything is fine, but if I make it on the fly, the locale is the default.

**Comment by sebastienheyd** [comment]
Hello,

The tutorial will do the job, but you have one more step to make it work: you have to disable the `boilerplatelocale` middleware.

To do that, copy the file `vendor/sebastienheyd/boilerplate/src/routes/boilerplate.php` in `/routes`, edit the copied file and remove `boilerplatelocale` from `middleware` in `$default`.

After that, declare your own middleware like in the tutorial and it should work.

I may be inspired by the tutorial to make a system to change the language from the administration panel.

**Comment by sebastienheyd** [comment]
https://github.com/sebastienheyd/boilerplate/commit/43927ac5280db3241d994f6a768c5a64aef5190c

I'm on the way to add a language switcher.

I think the solution of using the session is not the better way. I think we should store the preferred language by user in the database directly. 

So the language will be loaded for each user on login and it will avoid user to reselect his preferred language after each login.

**Comment by sebastienheyd** [comment]
Have a look to the new 7.5.5 release : https://github.com/sebastienheyd/boilerplate/releases/tag/7.5.5

I opted to store a cookie instead of storing into session or database. And I added the switch to the login page in addition to the top bar.
