### ISSUE TITLE
[ADD] Email verification

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#48]
Hi, thanks for this amazing boilerplate.
Would be possible add an email verification system for the registration?

Thanks

**Comment by sebastienheyd** [comment]
Hi, thanks for your support!

What do you mean by checking the validity of the e-mail?

There is already a check on the e-mail format with the [email](https://laravel.com/docs/8.x/validation#rule-email) validation rule, but as you can see it's possible to set more precise rules (dns, spoof, ...).

See [line 62 of the RegisterController](https://github.com/sebastienheyd/boilerplate/blob/c82c7bd9dab62427cba0a8a816925a83722567ec/src/Controllers/Auth/RegisterController.php#L62)

Another solution would be to enter only the email address and send a unique and temporary link for registration. The risk in this case is especially if the e-mail does not arrive for some reason, the user cannot register.

**Comment by cod3rshotout** [comment]
@sebastienheyd Hi, thanks for the answer!
Sorry, I was a bit unclear. I mean to send a confirmation e-mail to the new user, [check the doc](https://laravel.com/docs/8.x/verification).

I'm new to Laravel and I'm learning it from your boilerplate, I would like to know if you could add this mechanism as default.

Thanks

**Comment by sebastienheyd** [comment]
OK stay tuned...

**Comment by sebastienheyd** [comment]
Done ! See the [documentation](https://sebastienheyd.github.io/boilerplate/configuration/auth#verify_email)

Maybe you have to scaffold again in your case.
