### ISSUE TITLE
filterfilterOptions not working with space

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#51]
Hi, I'm facing a weird situation, essentially I have this Datatable Column:

```
Column::add(__('invites.status.title'))
->width('100px')
->data('status', function (Invite $invite) {
    $badge = '<span class="badge badge-pill badge-%s">%s</span';
    if ($invite->status == 'accepted') {
        return sprintf($badge, 'success', __('invites.status.accepted'));
    } else if ($invite->status == 'not_accepted') {
        return sprintf($badge, 'danger', __('invites.status.not_accepted'));
    }

    return sprintf($badge, 'warning', __('invites.status.waiting'));
})
->filterOptions([
    __('invites.status.accepted'),
    __('invites.status.waiting'),
    __('invites.status.not_accepted'),
]),
```

the `invites` locale array contains this:

    'status'            => [
        'title'         => 'Stato',
        'not_accepted'  => 'Non accettato',
        'accepted'      => 'Accettato',
        'waiting'       => 'In attesa',
    ],

If I select: 'accepted', the rows are filtered correctly, if I select 'waiting' or 'not_accepted' which contains space inside the string, no records is returned.

**Comment by sebastienheyd** [comment]
Hi,

You have to use an associative array : 

```php
->filterOptions([
   'accepted' =>  __('invites.status.accepted'),
   'waiting' =>  __('invites.status.waiting'),
   'not_accepted' =>  __('invites.status.not_accepted'),
]),
```

This will use the keys as options values.
