### ISSUE TITLE
[Future Request] Optional menu icon 

### ISSUE THREAD

**Issue by yudistirasd** [sebastienheyd/boilerplate#55]
Hey @sebastienheyd! Thank you for your work. Is really save my time.
I want use another icon or just an image on the menu, can you make it?

for now, i use prepend method from laravel-menu and make little changes to disable the default icon.

![image](https://user-images.githubusercontent.com/25135334/156502114-8289a987-6964-4497-8e99-0b36c69e6df0.png)
![image](https://user-images.githubusercontent.com/25135334/156502177-d75078d9-393d-462b-84ac-e6495c40a8a5.png)

**Comment by sebastienheyd** [comment]
Ok, I will see what I can do
