### ISSUE TITLE
Route [verification.notice] not defined.

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#56]
If I use the `verified` middleware:

    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }

I get:

>Route [verification.notice] not defined.

The problem seems to be related to the boilerplate route file, in particular to this line:

    'as'         => 'boilerplate.',

So if I remove `boilerplate.` the error goes away but then I get:

>Route [boilerplate.verification.send] not defined.

Could you please look into this?

Thanks in advance

**Comment by sebastienheyd** [comment]
You have to use `boilerplate.emailverified` instead of `verified`

The middleware will redirect to `boilerplate.verification.notice` instead of `verification.notice`
