### ISSUE TITLE
[enhancement] Could we have textarea component?

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#58]
Hi,

I saw there is the TinyMCE component which is great, but sometimes we just need to add notes to a particular field and we don't need markup feature. Could you please add the Textarea component too so we don't have to craft it manually?

Thanks

**Comment by sebastienheyd** [comment]
Hi,

I have to add this to the documentation, you can specify textarea as type of the input with the component `<x-boilerplate::input>` :

```blade
<x-boilerplate::input type="textarea" name="name" label="My textarea" />
```
