### ISSUE TITLE
How to set total records and offset from server side datatable?

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#61]
I'm using an API service that returns only 50 records per request, so I need to use the Datatable pagination and set the total records.
I searched for setTotalRecords within your boilerplate but there is no implementation.

I found this on the official repo of yajra datatable: https://github.com/yajra/laravel-datatables/pull/2083

Do you thinks is possible add this behavior? It would be very useful

Thanks

**Comment by sebastienheyd** [comment]
Added, [see documentation here](https://sebastienheyd.github.io/boilerplate/datatables/datasource#api)
