### ISSUE TITLE
Cannot declare class Sebastienheyd\Boilerplate\Datatables\Admin\UsersDatatable

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#63]
This issue happen when we use the `scaffhold` command, so we have a copy of UsersDatatable and RolesDatatable within our `Datatables` directory.

The `BoilerplateServiceProvider` actually register these two Datatables using this line:

    app('boilerplate.datatables')->registerDatatable(UsersDatatable::class, RolesDatatable::class);

So if I call the datatable component I get the error above. I think is not necessary instantiate the UsersDatatable and RolesDatatable by default, or maybe I'm missing something in this logic.

Again, this happen only for the scaffhold.

**Comment by sebastienheyd** [comment]
When you scaffold, the classes in `app/Datatables` will overload default classes.

This happens in the [DatatableComposer.php file](https://github.com/sebastienheyd/boilerplate/blob/e372e8c55fa6d907e7d365135e8455b41753afcf/src/View/Composers/DatatableComposer.php#L21)

Have you check if the namespaces are good in the files in `app/Datatables` ? Can you send the stacktrace ?
