### ISSUE TITLE
Datatable returns empty data when used with a filter

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#64]
Hi, I'm using the latest method added to the boilerplate: `setTotalRecords` and `setOffset` in this way:

```
public function datasource()
{
    $search = request()->post('search');
    $start = request()->post('start');
    $length = request()->post('length');

    $response = $this->packages::searchByDrugName([
        'page' => $start / $length,
        'name' => $search['value']
    ]);

    $this->setOffset($response['to']);
    $this->setTotalRecords($response['total']);

    return $response['data'];
}
```

I'm calling an external API service through an SDK, and when the DataTable loads I can see all the rows correctly, this is the `$response` value [(check on pastebin)](https://pastebin.com/U9qxqAeh).

When I type something in the search bar, eg "idro", I get this `$response` value[(check on pastebin)](https://pastebin.com/Cm4bXDNQ).

The problem's that after the second call, so when I valorized the search bar with "idro", I doesn't get any rows displayed even if the response has returned data. This is the response returned:

![Immagine 2022-04-01 175607](https://user-images.githubusercontent.com/72454584/161299273-ef61ba97-921e-4244-95a1-f1ac0c231437.jpg)

I initially though that was a problem of the API, but I tried to add this before `searchByDrugName`: `$search['value'] = 'idro';`. So I have simulated the search type of "idro" without typing anything in the search box, and the Datatable has returned the expected rows.

I guess there is a conflict somewhere that prevent the DataTable to return the data array when the search box is filled, specifically when the method `setOffset` and `setTotalRecords` are used.

Could you kindly look into this?

Thanks

**Comment by sebastienheyd** [comment]
Can you try this : 

```php
return collect($response['data']);
```

**Comment by cod3rshotout** [comment]
> Can you try this :
> 
> ```
> return collect($response['data']);
> ```

I get this:

![Immagine 2022-04-06 145504](https://user-images.githubusercontent.com/72454584/161979331-666980e1-fde7-4b11-94ab-c09e912b081d.png)

**Comment by cod3rshotout** [comment]
> Can you update the package to the latest version and try to fix your datatable by adding `setFilteredRecords` like in the [documentation](https://sebastienheyd.github.io/boilerplate/datatables/datasource#api)

Download the latest release but same empty data unfortunately. I have this code:

```
public function datasource()
{
    $search = request()->post('search');
    $start = request()->post('start');
    $length = request()->post('length');

    $response = $this->packages::searchByDrugName([
        'page' => $start / $length,
        'name' => $search['value']
    ]);

    $this->setOffset($start)
        ->setTotalRecords($response['total'])
        ->setFilteredRecords($response['total']);

    return collect($response['data']);
}
```

Getting this in console:

![1](https://user-images.githubusercontent.com/72454584/162272595-ecfd5ed9-a414-47f1-bb63-263f407a67a3.png)

This is the class of the client that returns the result from `searchByDrugName`:

```
<?php

namespace Razen\Aifa\Services;

use Proxevent\Aifa\API;
use Proxevent\Aifa\Helpers\APIHelper;

class Packages
{
    protected static $endpoint = 'packages/';

    /**
     * Get drugs by name
     * 
     * @param array $filters
     * 
     * @return array
     */
    public static function searchByDrugName(array $filters = []): array
    {
        $endpoint = self::$endpoint . APIHelper::addQueryFilters($filters);
        return API::get($endpoint);
    }
}
```


```
<?php

namespace Razen\Aifa;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ServerException;

class API
{
    public static function get(string $apiEndpoint, bool $pager = false): array
    {
        $baseUrl = env("AIFA_API_ENDPOINT");
        if (empty($baseUrl)) {
            throw new \Exception("AIFA_API_ENDPOINT non setted");
        }

        $endpoint = $baseUrl . "/" . $apiEndpoint;

        try {
            $client = new Client();
            $response = $client->request('GET',  $endpoint, [
                'headers' => [
                    'Accept' => 'application/json',
                    'Authorization' => "Bearer " . Configuration::getToken(),
                ],
            ]);
        } catch (ClientException $e) { // 400

            $response = $e->getResponse();
            $statusCode = $response->getStatusCode();

            // not authenticated
            if ($statusCode == 401) {
                self::refreshClientAccessToken();
                return self::get($apiEndpoint, $pager);
            }

            return json_decode($response->getBody()->getContents());
        } catch (ServerException $e) { //500
            var_dump($e);
            die();
        }

        return json_decode($response->getBody(), true);
    }

    private static function refreshClientAccessToken()
    {
        try {
            $client = new Client();
            $response = $client->request('POST', env("AIFA_API_ENDPOINT") . "/login", [
                'headers' => [
                    'Accept' => 'application/json',
                ],
                'json' => [
                    'email' => env("AIFA_API_USERNAME"),
                    'password' => env("AIFA_API_PWD")
                ]
            ]);
        } catch (GuzzleException $e) {
            $response = $e->getResponse();
            $statusCode = $response->getStatusCode();

            if ($statusCode == 401) {
                throw new \Exception("Invalid credentials");
            }
        }

        $response = json_decode($response->getBody(), true);
        Configuration::setToken($response['token']);

        return true;
    }
}
```

**Comment by sebastienheyd** [comment]
Do you use the `stateSave` option ? If you use it, maybe you have an old search in memory.

Install the [Laravel debug bar](https://packagist.org/packages/barryvdh/laravel-debugbar) and send the `$result['data']` to it. I will be easier to see what the API returns.

```php
public function datasource()
{
    ...

    debug($response['data']); // <= here

    return collect($response['data']);
}
```

Check the `Messages` tab in the debug bar.

**Comment by cod3rshotout** [comment]
> Do you use the `stateSave` option ? If you use it, maybe you have an old search in memory.
> 
> Install the [Laravel debug bar](https://packagist.org/packages/barryvdh/laravel-debugbar) and send the `$result['data']` to it. I will be easier to see what the API returns.
> 
> ```
> public function datasource()
> {
>     ...
> 
>     debug($response['data']); // <= here
> 
>     return collect($response['data']);
> }
> ```
> 
> Check the `Messages` tab in the debug bar.

I'm not using the `stateSave` option, this is the Datatable setup:

    public function setUp()
    {
        $this->packages = new Packages();

        $this
            ->showCheckboxes()
            ->condensed()
            ->pageLength(15)
            ->noLengthChange()
            ->noSorting()
            ->buttons([]);
    }

So I added this line: `debug($response['data']);`

and I got a correct response from the debug bar:

![Immagine 2022-04-08 112147](https://user-images.githubusercontent.com/72454584/162406674-3bca1a8d-aa1f-4c66-9389-9306f440eb21.png)

But the Datatable still showing an empty result

**Comment by sebastienheyd** [comment]
Update to the latest version and try with skipPaging

```php
public function datasource()
{
    $search = request()->post('search');
    $start = request()->post('start');
    $length = request()->post('length');

    $response = $this->packages::searchByDrugName([
        'page' => $start / $length,
        'name' => $search['value']
    ]);

    $this->setOffset($start)
        ->setTotalRecords($response['total'])
        ->setFilteredRecords($response['total'])
        ->skipPaging();

    return collect($response['data']);
}
```

**Comment by sebastienheyd** [comment]
In the LICENSE file... contact@sheyd.fr

**Comment by cod3rshotout** [comment]
@sebastienheyd I sent you an email with the demo application, you just need to serve the app and go to dashboard, let me know if you need more details
