### ISSUE TITLE
how to crud ?

### ISSUE THREAD

**Issue by andrinda** [sebastienheyd/boilerplate#7]
haii admin ,you can give me sample crud with boilerplate?

**Comment by sebastienheyd** [comment]
Hello,

At the moment there is no scaffolding available to automate the CRUD in boilerplate. I'm looking for interesting packages for this...

However, to make it simple here's how I do it (I assume that tables and models are already created)

* First,[ I create a seeder](https://laravel.com/docs/5.6/seeding#writing-seeders) to add the necessary permissions to my new section in the permission table.

* Then [I create the controller](https://laravel.com/docs/5.6/controllers#resource-controllers) linked to the resource.

* In the file routes/web.php I add a group "admin" ([see the second group here](/sebastienheyd/boilerplate/blob/5.6/src/routes/boilerplate.php)) and a route to the controller of the resource in this group.

* Finally I add an item in the menu with the command `php artisan boilerplate: menuitem`

Now all you have to do is code ! :)

Here are a few tips for the moment, I plan to create a wiki to better document the package. I also have a second package in preparation that works with boilerplate in which there will be a lot of examples...

Stay tuned !

**Comment by diorz38** [comment]
Can you check crestApp, that is a crud generator, have good doc too

**Comment by ruospo** [comment]
i have create the controller and route and work very nice, but when add i menu item 
the menu not find route.
