### ISSUE TITLE
How to set min and max date using Carbon on datetimepicker?

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate#74]
I cannot find any example in the documentation, I want set minDate and maxDate using carbon:

https://getdatepicker.com/5-4/Options/#mindate

**Comment by sebastienheyd** [comment]
You have to use a non-primitive value by using `:options`, it's not convenient but it works :

```html
<x-boilerplate::datetimepicker name="test" :options="'minDate:\''.\Illuminate\Support\Carbon::now()->format('Y-m-d').'\''" />
```
