### ISSUE TITLE
Using boilerplate on a subdomain

### ISSUE THREAD

**Issue by sonicalabs** [sebastienheyd/boilerplate#8]
Hi Sebastien, how its going !!

Only as a suggestion, for future releases.
Currently I'm working on a little project and I choose to have boilerplate separated from web URL and have his own subdomain. Laravel support subdomain routing, so I add a line to app/config.php

'domain'  => 'http://sudomain.domain.tld' // Use your own http(s)://subdomain
'prefix'     => '', // Set no null for root url

And in Boilerplate route file add this to $default array
'domain' => config('boilerplate.app.domain','')

Only rest to configure Apache or Nginx adding subdomain.domain.tld as an alias of vhost to have bolierplate separated from web url's. Tested and working out of the box.

Maybe someone find this useful and u can add in next updates.
Regards

**Comment by sebastienheyd** [comment]
Hey !

Hmmm, interresting... I will try it asap.

I will certainly add this feature soon, stay tuned more will come... ;)

Thanks !

**Comment by sonicalabs** [comment]
u're welcome !! :)

**Comment by sebastienheyd** [comment]
I just added this feature : [5.6.5](https://github.com/sebastienheyd/boilerplate/tree/5.6.5)
