### ISSUE TITLE
[Question] - How to remove default menu items

### ISSUE THREAD

**Issue by Faber44** [sebastienheyd/boilerplate#82]
Hello and thanks for your boilerplate :)
Should be simple and easy, but how do you remove default menu items (like logs and users) without touching the vendor files ?

**Comment by sebastienheyd** [comment]
Hello,

The easiest way to remove the logs menu item is to set `logs => false` in the `config/boilerplate/app.php`.

Or you can unregister menu items in the `boot` method in  `app/Providers/AppServiceProvider.php` :

```php
public function boot()
{
  app('boilerplate.menu.items')
      ->unregisterMenuItem("Sebastienheyd\Boilerplate\Menu\Users")
      ->unregisterMenuItem("Sebastienheyd\Boilerplate\Menu\Logs");
}
```
