### ISSUE TITLE
Suggestion to convert package into a Vue version

### ISSUE THREAD

**Issue by abdallhsamy** [sebastienheyd/boilerplate#86]
Hi @sebastienheyd 

I recently came across package. I think it's a great package and it has a lot of useful features for building admin panels. However, I noticed that it's built using Blade templates, which may not be as flexible as Vue components.

Therefore, I would like to suggest that you consider converting this package into a Vue version. Vue is a popular JavaScript framework that is known for its ease of use and flexibility, and it would allow developers to customize the package more easily. Plus, Vue is becoming more popular among Laravel developers, so it would be a great addition to your package.

If you decide to move forward with this suggestion, I would be happy to contribute to the project and help with testing and feedback.

Thank you for your consideration!

Best regards

**Comment by sebastienheyd** [comment]
Hi @abdallhsamy 

For the moment I'm not in favour of js frameworks for backend, current components use native js plugins in their purest form, I don't think adding an overlay would bring any benefit, knowing that on top of that the components are already fully customizable very easily (and that's the most important).

Maybe I'm wrong, I suggest you to fork the project and modify or create a component to see if there is a real interest to do it. If I am convinced then I will see what I can do.
