### ISSUE TITLE
Textarea option not working in input component

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#87]
Hello! I've recently updated to the latest version but if i pass type="textarea" to the input option, but the result is the ordinary input with type="textarea" as a attrubute, no <textarea></textarea> as espected.

**Comment by sebastienheyd** [comment]
Hello, you're absolutely right. By changing deprecated laravelcollective/html to spatie/html this won't work anymore. I will fix this very quickly.
