### ISSUE TITLE
Impersonate - too many redirects

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#88]
Often I receive this error when trying to use the impersonate function. In order to work again I must delete the cookies.

**Comment by sebastienheyd** [comment]
Certainly linked to this PR : https://github.com/sebastienheyd/boilerplate/pull/77

I don't write this feature, but I will write tests on it now :)

**Comment by sebastienheyd** [comment]
Can you test the latest version and say if it's ok ?

**Comment by thracefields** [comment]
Yes, everthing is now fine. Thank you!

**Comment by thracefields** [comment]
Yes, everything is now fine. Thank you!
