### ISSUE TITLE
Suggestion: Add Justify plugin to CKEditor

### ISSUE THREAD

**Issue by sonicalabs** [sebastienheyd/boilerplate#9]
Hi Again Sebastien
I manually integrate Justify plugin to CKEditor https://ckeditor.com/cke4/addon/justify. Would be great if can be added in base installation. I only added folder plugin and define as an extra parameter on CKEDITOR.replace() instance

CKEDITOR.replace( 'description',
            {
                extraPlugins : 'justify'
            });

, but I think after update boilerplate and publish public tag maybe plugin folder is deleted. I'm right? Or its safe to do this way?

I try to add to my fork, but I'm new to webpack/mixin/assets procedure.. and I have to learn how to integrate well to make your pull requests easely !! :)

**Comment by sebastienheyd** [comment]
Hey !

I haven't joined CKEditor yet.

I didn't do it to make the package heavier and also to leave the choice, some prefer to use TinyMCE for example. I would have to integrate both in this case... I would never finish integrating scripts in this case.

I was thinking of integrating them the day I would create a "CMS" package based on Boilerplate.
