### ISSUE TITLE
Datatable row color

### ISSUE THREAD

**Issue by nicopoal** [sebastienheyd/boilerplate#91]
Hi,
By default, datatable puts the "even" and "odd" classes on the rows. I'd like to be able to customize the color (or classnames) of each row according to the values of a column in the row (for example, for a status, green for finished, red for late). Is this possible? 
Thanks for your help

**Comment by sebastienheyd** [comment]
Hi,

Yes, this is possible by using the setRowClass method : https://sebastienheyd.github.io/boilerplate/datatables/options#setrowclass
