### ISSUE TITLE
Remove keep-alive session

### ISSUE THREAD

**Issue by thracefields** [sebastienheyd/boilerplate#95]
Hello! Is there a way to remove js keep-alive session so I can use session_lifetime (built in Laravel) and log out users after the session expires? Thank you!

**Comment by sebastienheyd** [comment]
Not at the moment, but I can plan to make it optional through the configuration file.

**Comment by mmrtonmoybd** [comment]
#100 
What if I login my user ID on my friend's device and forget to logout? Then my friend will access my user ID without my permission because there is no way to logout his device from my device

**Comment by mmrtonmoybd** [comment]
@sebastienheyd 
#100 
What if I login my user ID on my friend's device and forget to logout? Then my friend will access my user ID without my permission because there is no way to logout his device from my device and my friend's device will not be logout until press the logout button.

**Comment by sebastienheyd** [comment]
> @sebastienheyd #100 What if I login my user ID on my friend's device and forget to logout? Then my friend will access my user ID without my permission because there is no way to logout his device from my device and my friend's device will not be logout until press the logout button.

Can you create a new issue for this? There is certainly a way to invalidate the other sessions.

In the meantime, for now you can do this:

- setting keepalive option inf config/boilerplate/app.php to false
- setting SESSION_EXPIRE_ON_CLOSE in your .env file to true

Optionally setting SESSION_LIFETIME in your .env to a lower value
